#!/usr/bin/env sh
# @TODO \n are missing in the resulting podfile when command is run

DEFAULT_PFILE_NAME="PODFILE"

usage() {
  echo "Usage: p [ -a pod_name | -o pod_options | -p pattern | -g group | -t target | -f filepath | -d debug]"
  exit 2
}

set_pattern() {
  if [[ ! -z "${pattern}" ]]; then
    echo "Pattern is already set"
    usage
  fi

  type=$1
  shift

  if [[ $type == "pattern" ]]; then
    pattern="$@"
  elif [[ $type == "group" ]]; then
    pattern="((def)|(#)) $@"
  elif [[ $type == "target" ]]; then
    pattern="(abstract_)?target '$@' do"
  else
    echo "Unknown variable name passed"
  fi
}

while getopts 'a:o:f:p:g:t:?hd' c
do
  case $c in
    a) pod_name=$OPTARG ;;
    o) pod_options=$OPTARG ;;
    f) filepath=$OPTARG ;;
    p) set_pattern pattern $OPTARG ;;
    g) set_pattern group $OPTARG ;;
    t) set_pattern target $OPTARG ;;
    d) debug=true ;;
    h|?) usage ;;
 esac
done

if [[ -z "${pod_name}" ]]; then
    usage
    exit
fi

if [[ ! -z "$filepath" && -f "$filepath" ]]; then
  :
elif [[ -f $DEFAULT_PFILE_NAME ]]; then
  filepath=$DEFAULT_PFILE_NAME
else
  echo "No Podfile found"
  exit
fi

if [[ "$type" == "target" || ("$type" == "pattern" && "$pattern" != "root")]]; then
    indent=true  
else
    indent=false
fi


SRC="${BASH_SOURCE[0]}"
SRC="$(realpath "${SRC}")"
DIR="$(dirname "${SRC}")" 
output=$(gawk -v pod_name="$pod_name" -v pod_options="$pod_options" -v pattern="$pattern" -v indent=$indent -e "$(cat $DIR/p.awk)" $filepath)

if [[ $debug ]]; then
    echo "$output"
else
    echo "$output" > $filepath
fi
